{"level":"info","ts":"2024-11-17T00:23:40Z","msg":"barman-cloud-check-wal-archive checking the first wal","logging_pod":"blocky-cnpg-main-1-full-recovery"}
{"level":"info","ts":"2024-11-17T00:23:41Z","logger":"barman-cloud-check-wal-archive","msg":"2024-11-17 00:23:41,929 [20] ERROR: WAL archive check failed for server blocky-cnpg-main-r1: Expected empty archive","pipe":"stderr","logging_pod":"blocky-cnpg-main-1-full-recovery"}
{"level":"error","ts":"2024-11-17T00:23:41Z","msg":"Error invoking barman-cloud-check-wal-archive","logging_pod":"blocky-cnpg-main-1-full-recovery","currentPrimary":"","targetPrimary":"blocky-cnpg-main-1","options":["--endpoint-url","https://50998380d7c89b6f2d6b9c2b0f0840e1.r2.cloudflarestorage.com","--cloud-provider","aws-s3","s3://app-backup/blocky/cnpg","blocky-cnpg-main-r1"],"exitCode":-1,"error":"exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/barman/archiver.(*WALArchiver).CheckWalArchiveDestination\n\tpkg/management/barman/archiver/archiver.go:257\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.(*InitInfo).checkBackupDestination\n\tpkg/management/postgres/restore.go:950\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/postgres.InitInfo.Restore\n\tpkg/management/postgres/restore.go:254\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:90\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:63\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\tcmd/manager/main.go:66\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/proc.go:271"}
{"level":"error","ts":"2024-11-17T00:23:41Z","msg":"Error while restoring a backup","logging_pod":"blocky-cnpg-main-1-full-recovery","error":"unexpected failure invoking barman-cloud-wal-archive: exit status 1","stacktrace":"github.com/cloudnative-pg/cloudnative-pg/pkg/management/log.(*logger).Error\n\tpkg/management/log/log.go:125\ngithub.com/cloudnative-pg/cloudnative-pg/pkg/management/log.Error\n\tpkg/management/log/log.go:163\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.restoreSubCommand\n\tinternal/cmd/manager/instance/restore/cmd.go:92\ngithub.com/cloudnative-pg/cloudnative-pg/internal/cmd/manager/instance/restore.NewCmd.func2\n\tinternal/cmd/manager/instance/restore/cmd.go:63\ngithub.com/spf13/cobra.(*Command).execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:985\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1117\ngithub.com/spf13/cobra.(*Command).Execute\n\tpkg/mod/github.com/spf13/cobra@v1.8.1/command.go:1041\nmain.main\n\tcmd/manager/main.go:66\nruntime.main\n\t/opt/hostedtoolcache/go/1.22.6/x64/src/runtime/proc.go:271"}
